version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: patornatmongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PATORNAT_MONGODB_ROOT_USERNAME} # root username
      MONGO_INITDB_ROOT_PASSWORD: ${PATORNAT_MONGODB_ROOT_PASSWORD} # root password
      MONGO_INITDB_DATABASE: ${PATORNAT_MONGODB_INITDB_DATABASE} # in this case it is patornat
      PATORNAT_MONGODB_USERNAME: ${PATORNAT_MONGODB_USERNAME} # For creation of r/w user
      PATORNAT_MONGODB_PASSWORD: ${PATORNAT_MONGODB_PASSWORD} # password for r/w user
      PATORNAT_MONGODB_DATABASE: ${PATORNAT_MONGODB_DATABASE} # database the user will have r/w access to
    volumes:
      - mongodata:/data/db
      - ./database/db-init/:/docker-entrypoint-initdb.d
    ports:
      - ${PATORNAT_MONGODB_PORT}:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${PATORNAT_MONGODB_ROOT_USERNAME} #root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PATORNAT_MONGODB_ROOT_PASSWORD} #testpassword
  
  analysis_backend:
    image: docker.pkg.github.com/histographer/analysis-rest-api/analysis-rest-api:latest
    container_name: analysis_backend_test
    restart: always
    expose:
      - 9000
  
  patornatbackend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patornatbackend
    ports:
      - 9292:8080
    environment:
      PATORNAT_MONGODB_HOST: patornatmongo
      PATORNAT_MONGODB_PORT: 27017
      PATORNAT_MONGODB_USERNAME: ${PATORNAT_MONGODB_ROOT_USERNAME}
      PATORNAT_MONGODB_PASSWORD: ${PATORNAT_MONGODB_ROOT_PASSWORD}
      PATORNAT_MONGODB_DATABASE: ${PATORNAT_MONGODB_DATABASE}
      PATORNAT_ANALYSIS_BACKEND_PROTOCOL: http
      PATORNAT_ANALYSIS_BACKEND_HOST: analysis_backend_test
      PATORNAT_ANALYSIS_BACKEND_PORT: 9000

volumes:
  mongodata:
