version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: patornatmongo_test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PATORNAT_TEST_MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PATORNAT_TEST_MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${PATORNAT_TEST_MONGODB_INITDB_DATABASE}
      PATORNAT_MONGODB_USERNAME: ${PATORNAT_TEST_MONGODB_USERNAME} # For creation of r/w user
      PATORNAT_MONGODB_PASSWORD: ${PATORNAT_TEST_MONGODB_PASSWORD} # password for r/w user
      PATORNAT_MONGODB_DATABASE: ${PATORNAT_TEST_MONGODB_DATABASE} # database the user will have r/w access to
    volumes:
      - mongodata:/data/db
      - ./database/db-init/:/docker-entrypoint-initdb.d
    ports:
      - ${PATORNAT_TEST_MONGODB_PORT}:27017

  patornatbackend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patornatbackend_test
    ports:
      - ${PATORNAT_TEST_TOMCAT_PORT}:8080
    environment:
      PATORNAT_MONGODB_HOST: patornatmongo_test
      PATORNAT_MONGODB_PORT: 27017
      PATORNAT_MONGODB_USERNAME: ${PATORNAT_TEST_MONGODB_USERNAME}
      PATORNAT_MONGODB_PASSWORD: ${PATORNAT_TEST_MONGODB_PASSWORD}
      PATORNAT_MONGODB_DATABASE: ${PATORNAT_TEST_MONGODB_DATABASE}

volumes:
  mongodata:
