version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: compare_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME} # root username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD} # root password
      MONGO_INITDB_DATABASE: ${MONGODB_INITDB_DATABASE}
      COMPARE_MONGODB_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME} # For creation of r/w user
      COMPARE_MONGODB_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD} # password for r/w user
      COMPARE_MONGODB_DATABASE: ${MONGODB_INITDB_DATABASE} # database the user will have r/w access to
    volumes:
      - mongodata:/data/db
      - ./database/db-init/:/docker-entrypoint-initdb.d
    ports:
      - ${MONGODB_PORT}:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_INITDB_ROOT_USERNAME} #root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD} #testpassword

  # analysis_backend:
  #   image: docker.pkg.github.com/histographer/analysis-rest-api/analysis-rest-api:latest
  #   container_name: analysis_backend_test
  #   restart: always
  #   expose:
  #     - 8000

  web:
    build:
      context: ../analysis-rest-api
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 api.wsgi
    container_name: analysis
    volumes:
      - ../analysis-rest-api:/src
    ports:
      - '8000:8000'

  compare_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compare_backend
    ports:
      - 9292:8080
    environment:
      COMPARE_MONGODB_HOST: compare_mongo
      COMPARE_MONGODB_PORT: 27017
      COMPARE_MONGODB_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      COMPARE_MONGODB_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      COMPARE_MONGODB_DATABASE: ${MONGODB_INITDB_DATABASE}
      COMPARE_ANALYSIS_PROTOCOL: ${ANALYSIS_PROTOCOL}
      COMPARE_ANALYSIS_URL: ${ANALYSIS_URL}
      COMPARE_ANALYSIS_PORT: 8000
      COMPARE_CYTOMINE_URL: ${COMPARE_CYTOMINE_URL}
      COMPARE_ADMIN_PUB_KEY: ${COMPARE_ADMIN_PUB_KEY}
      COMPARE_ADMIN_PRIV_KEY: ${COMPARE_ADMIN_PRIV_KEY}

volumes:
  mongodata:
